# Puppet RSpec Tests asserting that a catalog for a given host is compliant with
# rules derived from a baseline catalog obtained for host: 'jenkins'
# Generated by: org.cloudsmith.geppetto.catalog.util.CatalogRspecGenerator
# Generated at: 14.9.2012

require 'spec_helper'

describe 'jenkins', :type => :host do
  # Set facts to empty hash, and expect them to be injected
  let(:facts) { { } }

  # Classes (in alphabetical order)
  it 'class jenkins' do
    should include_class('jenkins')
  end
  it 'class settings' do
    should include_class('settings')
  end

  # Resources per type and title (alphabetically)
  it 'resource stage main' do
    should contain_stage('main').with(
      'name' => 'main'
    )
  end
end
